affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: dungxbuns/vdt-lab-backend
  tag: v14
imagePullSecrets: []
ingress:
  annotations: {}
  className: ''
  enabled: false
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
livenessProbe:
  httpGet:
    path: /
    port: 80
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
postgresql:
  image:
    registry: docker.io
    repository: postgres
  resources: {}
  service:
    name: postgresql
    port: 5432
replicaCount: 1
resources: {}
secrets:
  data:
    DB_HOST: ZGI=
    DB_NAME: c3R1ZGVudHM=
    DB_PASS: YnVu
    DB_PORT: NTQzMg==
    DB_USER: cG9zdGdyZXM=
  name: api-secrets
  type: Opaque
securityContext: {}
service:
  nodePort: 30012
  port: 6868
  type: NodePort
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ''
tolerations: []
volumeMounts: []
volumes: []
